#!/usr/bin/env bash
# wp3 check: 030 C-checks against references, README and the refresh script
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/../../.."
fail=0
if rg -n -- '--session' aside-jun/references | rg -v 'removed'; then echo "--session live mention"; fail=1; fi
rg -q 'no escape flag' aside-jun && { echo "no escape flag"; fail=1; }
[ "$(rg -c 'save-sessions' aside-jun/references/scheduling.md)" -ge 2 ] || { echo "save-sessions"; fail=1; }
[ "$(rg -c 'getTabs' aside-jun/references/repl-api.md)" = "1" ] || { echo "getTabs"; fail=1; }
rg -q '1\.26\.(810|829)\.' aside-jun/references README.md && { echo "old full pin"; fail=1; }
[ "$(rg -c 'Write and edit files only under ~/.aside/u/0/' aside-jun/references/scheduling.md aside-jun/references/deep-research.md | awk -F: '{s+=$2} END{print s}')" = "2" ] || { echo "clause copies"; fail=1; }
bash -n aside-jun/scripts/refresh-builtin-summary.sh || fail=1
tmp=$(mktemp); cp aside-jun/references/builtin-skills.md "$tmp"
bash aside-jun/scripts/refresh-builtin-summary.sh >/dev/null
rg -q '\| Skill \| Backing \| CLI listed \| Purpose \|' aside-jun/references/builtin-skills.md || { echo "4-col header"; fail=1; }
rg -q '^34 top-level skills and 16 site-specific' aside-jun/references/builtin-skills.md || { echo "counts"; fail=1; }
rg -q '^\| `imessage` \| [a-z ]+ \| yes \|' aside-jun/references/builtin-skills.md || { echo "imessage alias"; fail=1; }
# regenerated file must equal the committed one apart from the date stamp
if ! diff <(rg -v '^Generated by' "$tmp") <(rg -v '^Generated by' aside-jun/references/builtin-skills.md) >/dev/null; then echo "builtin-skills drift"; fail=1; fi
cp "$tmp" aside-jun/references/builtin-skills.md; rm -f "$tmp"
git diff --check -- aside-jun README.md || fail=1
[ $fail -eq 0 ] && echo "wp3 check: OK"
exit $fail
