#!/usr/bin/env bash
# wp2 check: 020's C-checks against the tree
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/../../.."
fail=0
n=$(wc -l < aside-jun/SKILL.md | tr -d ' '); [ "$n" -eq 499 ] || { echo "SKILL.md $n lines, expected 499"; fail=1; }
rg -q 'daemon needs the GUI app' aside-jun/SKILL.md && { echo "v2-60 stale"; fail=1; }
rg -q 'for remote-host commands it need not be' aside-jun/SKILL.md || { echo "v2-60 fix missing"; fail=1; }
for p in 'session archive' 'session delete' '/exit'; do
  rg -q -- "$p" aside-jun/references/scheduling.md || { echo "missing: $p"; fail=1; }
done
[ "$(rg -c 'never write into it' aside-jun/references/scheduling.md)" = "1" ] || { echo "memory fence"; fail=1; }
rg -U -q 'can write\s+durable facts into' aside-jun/references/scheduling.md && { echo "v2-45 regression"; fail=1; }
rg -q -i 'writing memories' aside-jun/references/scheduling.md && { echo "residual write-memory wording"; fail=1; }
rg -q -- '--json' aside-jun/references/scheduling.md || { echo "memory --json"; fail=1; }
rg -q 'recall before asking' aside-jun/references/scheduling.md || { echo "recall-first"; fail=1; }
rg -q 'tell the user which skill' aside-jun/references/builtin-skills.md || { echo "skill notice"; fail=1; }
rg -q '^34 top-level skills and 16 site-specific' aside-jun/references/builtin-skills.md || { echo "counts"; fail=1; }
bash -n aside-jun/scripts/refresh-builtin-summary.sh || fail=1
tmp=$(mktemp); cp aside-jun/references/builtin-skills.md "$tmp"
bash aside-jun/scripts/refresh-builtin-summary.sh >/dev/null
diff <(rg -v '^Generated by' "$tmp") <(rg -v '^Generated by' aside-jun/references/builtin-skills.md) >/dev/null || { echo "builtin-skills drift"; fail=1; }
cp "$tmp" aside-jun/references/builtin-skills.md; rm -f "$tmp"
git diff --check || fail=1
[ $fail -eq 0 ] && echo "wp2 check: OK ($n SKILL.md lines)"
exit $fail
