#!/usr/bin/env bash
# Regenerate references/builtin-skills.md from the Aside account's installed builtin skills.
# Aside ships these and updates them with the app, so the summary drifts. Re-run after an update:
#   scripts/refresh-builtin-summary.sh [account-root]
#
# Layout note: builtin/ holds top-level skill directories, each with its own SKILL.md,
# plus one container directory (site-specific/) that has NO SKILL.md of its own and
# instead holds per-site skills one level deeper. Both are emitted, and the container
# itself is never listed as a loadable skill.
set -euo pipefail

ACCOUNT_ROOT="${1:-$HOME/.aside/u/0}"
BUILTIN_DIR="$ACCOUNT_ROOT/skills/builtin"
OUT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/references/builtin-skills.md"

if [ ! -d "$BUILTIN_DIR" ]; then
  echo "no builtin skills at $BUILTIN_DIR" >&2
  exit 1
fi

desc_of() {
  awk '/^description:/{sub(/^description:[[:space:]]*/,""); gsub(/^["'"'"']|["'"'"']$/,""); print; exit}' "$1" 2>/dev/null || true
}

# A skill is repl-backed when a JS global of the same shape exists in the repl scope.
REPL_BACKED=" chrome twitter x-twitter gmail google-gmail google-accounts google-docs google-sheets google-search notion slack linkedin youtube image-search imagegen apple-passwords captcha-solver aside "

top_count=0
site_count=0

top_rows=""
for f in "$BUILTIN_DIR"/*/SKILL.md; do
  [ -e "$f" ] || continue
  name=$(basename "$(dirname "$f")")
  d=$(desc_of "$f"); [ -z "$d" ] && d="(no description)"
  d=$(printf '%s' "$d" | cut -c1-130 | tr -d '|')
  if [[ "$REPL_BACKED" == *" $name "* ]]; then kind="repl global"; else kind="instructions"; fi
  top_rows+="| \`$name\` | $kind | $d |"$'\n'
  top_count=$((top_count+1))
done

site_rows=""
if [ -d "$BUILTIN_DIR/site-specific" ]; then
  for f in "$BUILTIN_DIR"/site-specific/*/SKILL.md; do
    [ -e "$f" ] || continue
    name=$(basename "$(dirname "$f")")
    d=$(desc_of "$f"); [ -z "$d" ] && d="(no description)"
    d=$(printf '%s' "$d" | cut -c1-130 | tr -d '|')
    site_rows+="| \`$name\` | $d |"$'\n'
    site_count=$((site_count+1))
  done
fi

{
  echo "# Aside builtin skills"
  echo
  echo "Generated by \`scripts/refresh-builtin-summary.sh\` from \`$BUILTIN_DIR\` on $(date +%Y-%m-%d)."
  echo "Aside owns these and ships updates with the app; re-run the script after an Aside update."
  echo
  echo "Only \`aside exec\` can load them. Codex cannot invoke one directly - name the skill in the"
  echo "exec prompt and let the Aside agent load it."
  echo
  echo "$top_count top-level skills and $site_count site-specific skills."
  echo
  echo "The \`Backing\` column says how the skill works. A \`repl global\` skill documents a JavaScript"
  echo "object you can also drive yourself from \`aside repl\`; several of those reach an API and never"
  echo "open a tab. An \`instructions\` skill is guidance for the agent with no matching global."
  echo
  echo "## Top-level"
  echo
  echo "| Skill | Backing | Purpose |"
  echo "|---|---|---|"
  printf '%s' "$top_rows"
  echo
  echo "## Site-specific"
  echo
  echo "Nested under \`site-specific/\`. The container directory has no SKILL.md and is not itself"
  echo "loadable; name the individual site skill instead."
  echo
  echo "| Skill | Purpose |"
  echo "|---|---|"
  printf '%s' "$site_rows"
} > "$OUT"

echo "wrote $OUT ($top_count top-level, $site_count site-specific)"
